services:
  postgres:
    image: postgres:16
    command: postgres -c track_activity_query_size=65536
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-b:
    image: postgres:17
    command: postgres -c track_activity_query_size=65536
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-ssl:
    build:
      context: dev/rds
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./dev/init.sql:/docker-entrypoint-initdb.d/init.sql
