-- Simulate an incident scenario.
-- Run each block in a separate psql session simultaneously.
--
-- Session 1 (long-running active query):
--   psql postgres://postgres:postgres@localhost:5432/postgres -c "SELECT pg_sleep(300);"
--
-- Session 2 (idle in transaction):
--   psql postgres://postgres:postgres@localhost:5432/postgres -c "BEGIN; SELECT 1;"
--   (do not commit — leave the session open)
--
-- Session 3 (blocking lock — run AFTER session 2 is open):
--   psql postgres://postgres:postgres@localhost:5432/postgres \
--     -c "BEGIN; LOCK TABLE seed_target IN ACCESS EXCLUSIVE MODE; SELECT pg_sleep(300);"
--
-- Session 4 (blocked by session 3):
--   psql postgres://postgres:postgres@localhost:5432/postgres \
--     -c "SELECT * FROM seed_target;"
